# These are supported funding model platforms

# github: [yourusername]
# patreon: yourusername
# open_collective: easy-country-icon
# ko_fi: yourusername
# custom: ['https://yourwebsite.com/donate']
